logistics:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      dataset: staging
      location: US
      threads: 4
      timeout_seconds: 300
      keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS', 'credentials/service-account.json') }}"

    prod:
      type: bigquery
      method: service-account
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      dataset: staging
      location: US
      threads: 8
      timeout_seconds: 600
      keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS') }}"
      priority: interactive
